export interface Race{
    key: string;
    name: string;
    str: number;
    dex: number;
    con: number;
    int: number;
    wis: number;
    cha: number;
    custom: boolean;
    addSingleBonus: boolean;
    note: string;
    d20SiteLink: string;
    archivesOfNethysLink: string;
}

export const Races: Race[] = [
    { key: 'human',            name: 'Human',                      str:  0, dex:  0, con:  0, int:  0, wis:  0, cha:  0, custom: false, addSingleBonus: true,  note: 'Add +2 to any one ability score', d20SiteLink: 'https://www.d20pfsrd.com/races/core-races/human',                                                        archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Human'      }, // Human
    { key: 'dwarf',            name: 'Dwarf',                      str:  0, dex:  0, con:  2, int:  0, wis:  2, cha: -2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/core-races/dwarf',                                                        archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Dwarf'      }, // Dwarf
    { key: 'elf',              name: 'Elf',                        str:  0, dex:  2, con: -2, int:  2, wis:  0, cha:  0, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/core-races/elf',                                                          archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Elf'        }, // Elf
    { key: 'gnome',            name: 'Gnome',                      str: -2, dex:  0, con:  2, int:  0, wis:  0, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/core-races/gnome',                                                        archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Gnome'      }, // Gnome
    { key: 'halfelf',          name: 'Half-Elf',                   str:  0, dex:  0, con:  0, int:  0, wis:  0, cha:  0, custom: false, addSingleBonus: true,  note: 'Add +2 to any one ability score', d20SiteLink: 'https://www.d20pfsrd.com/races/core-races/half-elf',                                                     archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Half-Elf'   }, // Half-Elf
    { key: 'halforc',          name: 'Half-Orc',                   str:  0, dex:  0, con:  0, int:  0, wis:  0, cha:  0, custom: false, addSingleBonus: true,  note: 'Add +2 to any one ability score', d20SiteLink: 'https://www.d20pfsrd.com/races/core-races/half-orc',                                                     archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Half-Orc'   }, // Half-Orc
    { key: 'halfling',         name: 'Halfling',                   str: -2, dex:  2, con:  0, int:  0, wis:  0, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/core-races/halfling',                                                     archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Halfling'   }, // Halfling
    { key: 'aasimar',          name: 'Aasimar',                    str:  0, dex:  0, con:  0, int:  0, wis:  2, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/featured-races/arg-aasimar',                                  archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Aasimar'    }, // Aasimar
    { key: 'aasimaragathion',  name: 'Aasimar (Agathion-Blooded)', str:  0, dex:  0, con:  0, int:  0, wis:  2, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-AASIMAR/#TOC-Agathion-Blooded-Idyllkin-',  archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Aasimar'    }, // Aasimar (Agathion-Blooded)
    { key: 'aasimarangel',     name: 'Aasimar (Angel-Blooded)',    str:  0, dex:  0, con:  0, int:  0, wis:  2, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-AASIMAR/#TOC-Angel-Blooded-Angelkin-',     archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Aasimar'    }, // Aasimar (Angel-Blooded)
    { key: 'aasimararchon',    name: 'Aasimar (Archon-Blooded)',   str:  0, dex:  0, con:  0, int:  0, wis:  2, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-AASIMAR/#TOC-Archon-Blooded-Lawbringers-', archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Aasimar'    }, // Aasimar (Archon-Blooded)
    { key: 'aasimarazata',     name: 'Aasimar (Azata-Blooded)',    str:  0, dex:  0, con:  0, int:  0, wis:  2, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-AASIMAR/#TOC-Azata-Blooded-Musetouched-',  archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Aasimar'    }, // Aasimar (Azata-Blooded)
    { key: 'aasimargaruda',    name: 'Aasimar (Garuda-Blooded)',   str:  0, dex:  0, con:  0, int:  0, wis:  2, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-AASIMAR/#TOC-Garuda-Blooded-Plumekith-',   archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Aasimar'    }, // Aasimar (Garuda-Blooded)
    { key: 'aasimarperi',      name: 'Aasimar (Pari-Blooded)',     str:  0, dex:  0, con:  0, int:  0, wis:  2, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-AASIMAR/#TOC-Peri-Blooded-Emberkin-',      archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Aasimar'    }, // Aasimar (Pari-Blooded)
    { key: 'catfolk',          name: 'Catfolk',                    str:  0, dex:  2, con:  0, int:  0, wis: -2, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/featured-races/arg-catfolk',                                  archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Catfolk'    }, // Catfolk
    { key: 'changeling',       name: 'Changeling',                 str:  0, dex:  0, con: -2, int:  0, wis:  2, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/uncommon-races/arg-changeling',                               archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Changeling' }, // Changeling
    { key: 'dhampir',          name: 'Dhampir',                    str:  0, dex:  2, con: -2, int:  0, wis:  0, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-DHAMPIR',                                  archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Dhampir'    }, // Dhampir
    { key: 'dhampirjiangshi',  name: 'Dhampir (Jinag-Shi-Born)',   str:  0, dex: -2, con:  0, int:  2, wis:  0, cha:  0, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-DHAMPIR/#jiang-shi-born_ru-shi',           archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Dhampir'    }, // Dhampir (Jinag-Shi-Born) (Ru-Shi)
    { key: 'dhampirmoroi',     name: 'Dhampir (Moroi-Born)',       str:  2, dex:  0, con: -2, int:  0, wis:  0, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-DHAMPIR/#moroi-born_svetocher',            archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Dhampir'    }, // Dhampir (Moroi-born) (Svetocher)
    { key: 'dhampirvetala',    name: 'Dhampir (Vetala-Born)',      str:  0, dex:  2, con:  0, int:  2, wis: -2, cha:  0, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-DHAMPIR/#vetala-born_ajibachana',          archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Dhampir'    }, // Dhampir (Vetala-born) (Ajibachana)
    { key: 'dhampirnosferatu', name: 'Dhampir (Nosferatu-Born)',   str:  2, dex:  0, con:  0, int:  0, wis:  2, cha:  0, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-DHAMPIR/#nosferatu-born_ancient-born',     archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Dhampir'    }, // Dhampir (Nosferatu-born) (Ancient-born)
    { key: 'drow',             name: 'Drow',                       str:  0, dex:  2, con: -2, int:  0, wis:  0, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/featured-races/arg-drow',                                     archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Drow'       }, // Drow
    { key: 'duergar',          name: 'Duergar',                    str:  0, dex:  0, con:  2, int:  0, wis:  2, cha: -4, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/uncommon-races/arg-duergar',                                  archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Duergar'    }, // Duergar
    { key: 'fetchling',        name: 'Fetchling',                  str:  0, dex:  2, con:  0, int:  0, wis: -2, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/featured-races/arg-fetchling',                                archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Fetchling'  }, // Fetchling
    { key: 'goblin',           name: 'Goblin',                     str: -2, dex:  4, con:  0, int:  0, wis:  0, cha: -2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/featured-races/arg-goblin',                                   archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Goblin'     }, // Goblin
    { key: 'hobgoblin',        name: 'Hobgoblin',                  str:  0, dex:  2, con:  2, int:  0, wis:  0, cha:  0, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/featured-races/arg-hobgoblin',                                archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Hobgoblin'  }, // Hobgoblin
    { key: 'ifrit',            name: 'Ifrit',                      str:  0, dex:  2, con:  0, int:  0, wis: -2, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/featured-races/arg-ifrit',                                    archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Ifrit'      }, // Ifrit
    { key: 'ifritmagma',       name: 'Ifrit (Magma)',              str:  0, dex: -2, con:  2, int:  2, wis:  0, cha:  0, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-IFRIT/#lavasoul_magma_ifrit',              archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Ifrit'      }, // Ifrit (Magma)
    { key: 'ifritsolar',       name: 'Ifrit (Solar)',              str:  2, dex:  0, con:  0, int:  0, wis: -2, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-IFRIT/#sunsoul_solar_ifrit',               archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Ifrit'      }, // Ifrit (Solar)
    { key: 'kistune',          name: 'Kistune',                    str: -2, dex:  2, con:  0, int:  0, wis:  0, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/uncommon-races/arg-kitsune',                                  archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Kitsune'    }, // Kistune
    { key: 'kobold',           name: 'Kobold',                     str: -4, dex:  2, con: -2, int:  0, wis:  0, cha:  0, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/featured-races/arg-kobold',                                   archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Kobold'     }, // Kobold
    { key: 'orc',              name: 'Orc',                        str:  4, dex:  0, con:  0, int: -2, wis: -2, cha: -2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/featured-races/arg-orc',                                      archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Orc'        }, // Orc
    { key: 'oread',            name: 'Oread',                      str:  2, dex:  0, con:  0, int:  0, wis:  2, cha: -2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/featured-races/arg-oread',                                    archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Oread'      }, // Oread
    { key: 'oreadcrystal',     name: 'Oread (Crystal)',            str:  2, dex:  0, con:  0, int:  0, wis: -2, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/featured-races/arg-Oread/#gemsoul_crystal_oread',             archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Oread'      }, // Oread (Crystal)
    { key: 'oreadmetal',       name: 'Oread (Metal)',              str:  0, dex: -2, con:  2, int:  0, wis:  2, cha:  0, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/featured-races/arg-Oread/#ironsoul_metal_oread',              archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Oread'      }, // Oread (Metal)
    { key: 'ratfolk',          name: 'Ratfolk',                    str: -2, dex:  2, con:  0, int:  2, wis:  0, cha:  0, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/featured-races/arg-ratfolk',                                  archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Ratfolk'    }, // Ratfolk
    { key: 'sylph',            name: 'Sylph',                      str:  0, dex:  2, con: -2, int:  2, wis:  0, cha:  0, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/featured-races/arg-sylph',                                    archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Sylph'      }, // Sylph
    { key: 'sylphfume',        name: 'Sylph (Fume)',               str:  0, dex:  2, con: -2, int:  0, wis:  0, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-SYLPH/#smokesoul_fume_sylph',              archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Sylph'      }, // Sylph (Fume)
    { key: 'sylphlightning',   name: 'Sylph (Lightning)',          str:  0, dex:  2, con:  0, int:  0, wis: -2, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-SYLPH/#stormsoul_lightning_sylph',         archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Sylph'      }, // Sylph (Lightning)
    { key: 'tengu',            name: 'Tengu',                      str:  0, dex:  2, con: -2, int:  0, wis:  2, cha:  0, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/featured-races/arg-tengu',                                    archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Tengu'      }, // Tengu
    { key: 'tiefling',         name: 'Tiefling',                   str:  0, dex:  2, con:  0, int:  2, wis:  0, cha: -2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/featured-races/arg-tiefling',                                 archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Tiefling'   }, // Tiefling
    { key: 'tieflingasura',    name: 'Tiefling (Asura-Spawn)',     str:  0, dex:  2, con:  0, int: -2, wis:  2, cha:  0, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-TIEFLING/#variant_tiefling_heritages',     archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Tiefling'   }, // Tiefling (Asura-Spawn)
    { key: 'tieflingdaemon',   name: 'Tiefling (Daemon-Spawn)',    str:  0, dex:  2, con:  0, int:  2, wis: -2, cha:  0, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-TIEFLING/#variant_tiefling_heritages',     archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Tiefling'   }, // Tiefling (Daemon-Spawn)
    { key: 'tieflingdemodand', name: 'Tiefling (Demodand-Spawn)',  str:  0, dex:  0, con:  2, int: -2, wis:  2, cha:  0, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-TIEFLING/#variant_tiefling_heritages',     archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Tiefling'   }, // Tiefling (Demodand-Spawn)
    { key: 'tieflingdemon',    name: 'Tiefling (Demon-Spawn)',     str:  2, dex:  0, con:  0, int: -2, wis:  0, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-TIEFLING/#variant_tiefling_heritages',     archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Tiefling'   }, // Tiefling (Demon-Spawn)
    { key: 'tieflingdevil',    name: 'Tiefling (Devil-Spawn)',     str:  0, dex:  0, con:  2, int:  0, wis:  2, cha: -2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-TIEFLING/#variant_tiefling_heritages',     archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Tiefling'   }, // Tiefling (Devil-Spawn)
    { key: 'tieflingdiv',      name: 'Tiefling (Div-Spawn)',       str:  0, dex:  2, con:  0, int: -2, wis:  0, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-TIEFLING/#variant_tiefling_heritages',     archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Tiefling'   }, // Tiefling (Div-Spawn)
    { key: 'tieflingkyton',    name: 'Tiefling (Kyton-Spawn)',     str:  0, dex:  0, con:  2, int:  0, wis: -2, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-TIEFLING/#variant_tiefling_heritages',     archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Tiefling'   }, // Tiefling (Kyton-Spawn)
    { key: 'tieflingoni',      name: 'Tiefling (Oni-Spawn)',       str:  2, dex:  0, con:  0, int:  0, wis:  2, cha: -2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-TIEFLING/#variant_tiefling_heritages',     archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Tiefling'   }, // Tiefling (Oni-Spawn)
    { key: 'tieflingqlippoth', name: 'Tiefling (Qlippoth-Spawn)',  str:  2, dex:  0, con:  0, int: -2, wis:  2, cha:  0, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-TIEFLING/#variant_tiefling_heritages',     archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Tiefling'   }, // Tiefling (Qlippoth-Spawn)
    { key: 'tieflingrakshasa', name: 'Tiefling (Rakshasa-Spawn)',  str:  0, dex:  2, con:  0, int:  0, wis: -2, cha:  2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-TIEFLING/#variant_tiefling_heritages',     archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Tiefling'   }, // Tiefling (Rakshasa-Spawn)
    { key: 'undine',           name: 'Undine',                     str: -2, dex:  2, con:  0, int:  0, wis:  2, cha:  0, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/races/other-races/featured-races/arg-undine',                                   archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Undine'     }, // Undine
    { key: 'undinefrost',      name: 'Undine (Frost)',             str:  0, dex:  2, con:  0, int:  2, wis:  0, cha: -2, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-UNDINE/#rimesoul_frost_undine',            archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Undine'     }, // Undine (Frost)
    { key: 'undinevapor',      name: 'Undine (Vapor)',             str:  0, dex:  0, con:  2, int: -2, wis:  2, cha:  0, custom: false, addSingleBonus: false, note: ''                               , d20SiteLink: 'https://www.d20pfsrd.com/RACES/OTHER-RACES/FEATURED-RACES/ARG-UNDINE/#mistsoul_vapor_undine',            archivesOfNethysLink: 'https://www.aonprd.com/RacesDisplay.aspx?ItemName=Undine'     }, // Undine (Vapor)
    { key: 'custom',           name: 'Custom',                     str:  0, dex:  0, con:  0, int:  0, wis:  0, cha:  0, custom: true,  addSingleBonus: false, note: 'Choose your own modifiers'      , d20SiteLink: '',                                                                                                       archivesOfNethysLink: ''                                                             } // Custom
];
